CREATE DATABASE [ColegioHogwartsDB]

USE [ColegioHogwartsDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Security](
	[IdSecurity] [int] IDENTITY(1,1) NOT NULL,
	[UserSecurity] [varchar](50) NOT NULL,
	[UserName] [varchar](100) NOT NULL,
	[PasswordUser] [varchar](200) NOT NULL,
	[RoleUser] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdSecurity] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Candidate](
	[IdCandidate] [int] IDENTITY(1,1) NOT NULL,
	[Identification] [bigint] NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[LastName] [varchar](20) NOT NULL,
	[Age] [int] NOT NULL,
	[House] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Candidate] PRIMARY KEY CLUSTERED 
(
	[IdCandidate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


